domains = {'scolomfr-voc-015-num-1179': {'label': 'arts plastiques',
                                         'edubases': ['Arts plastiques'],
                                         'scolomfr': ['arts plastiques',
                                                      'arts plastiques (cycle 3)',
                                                      'arts plastiques (cycle 4)',
                                                      'compétences travaillées (arts plastiques cycle 2)',
                                                      'compétences travaillées (arts plastiques cycle 3)',
                                                      'compétences travaillées (arts plastiques cycle 4)',
                                                      'arts plastiques (lycée 2015)',
                                                      'arts plastiques (enseignement de spécialité)',
                                                      'arts plastiques (enseignement optionnel)']},
           'scolomfr-voc-015-num-1548': {'label': 'enseignement moral et civique',
                                         'edubases': ['EMC'],
                                         'scolomfr': ['éducation civique',
                                                      'enseignement moral et civique (enseignement commun)',
                                                      'enseignement moral et civique (cycle 4)',
                                                      'enseignement moral et civique (discipline)',
                                                      'enseignement moral et civique (lycée 2015)',
                                                      'éducation civique',
                                                      'éducation civique, juridique et sociale'
                                                      ]},
           'scolomfr-voc-015-num-1032': {'label': 'éducation physique et sportive',
                                         'edubases': ['EPS'],
                                         'scolomfr': ['EPS',
                                                      'éducation physique et sportive (cycle 3)',
                                                      'éducation physique et sportive (cycle 4)',
                                                      'éducation physique et sportive (discipline)',
                                                      'éducation physique et sportive (lycée 2015)']},
           'scolomfr-voc-015-num-1333': {'label': 'français',
                                         'edubases': ['Français'],
                                         'scolomfr': ['français',
                                                      'français (CAP)',
                                                      'français (cycle 3)',
                                                      'français (cycle 4)',
                                                      'français (lycée 2015)',
                                                      'français (discipline)',
                                                      'français (enseignement commun)',
                                                      'français et histoire géographie',
                                                      'français et littérature',
                                                      'fle (français langue étrangère)',
                                                      'français (Bac Pro)',
                                                      'français (cycle 2)',
                                                      'français langue étrangère',
                                                      'français, histoire-géographie-éducation civique',
                                                      'comprendre le fonctionnement de la langue (cycle 3)',
                                                      'comprendre le fonctionnement de la langue (cycle 4)',
                                                      'lecture',
                                                      'lecture (français, cap)',
                                                      'lecture et compréhension de documents (français cycle 4)',
                                                      'lecture et compréhension de l\'écrit (français cycle 2)',
                                                      'lecture et compréhension de l\'écrit (français cycle 3)',
                                                      'culture littéraire et artistique (français cycle 3)',
                                                      'culture littéraire et artistique (français cycle 4)',
                                                      'écriture',
                                                      'écriture (cycle 1)',
                                                      'vocabulaire (français cycle 4)',
                                                      'vocabulaire',
                                                      'étude de la langue (grammaire, orthographe, lexique)'
                                                      ]},
           'scolomfr-voc-015-num-6360': {'label': 'langues et cultures de l\'Antiquité',
                                         'edubases': ['Grec ancien', 'Latin'],
                                         'scolomfr': ['latin',
                                                      'langues et cultures de l\'Antiquité (discipline)',
                                                      'Langues et cultures de l\'antiquité (grec)',
                                                      'langues et cultures de l\'Antiquité (enseignement facultatif cycle 4)',
                                                      'langues et cultures de l\'antiquité (latin)']},
           'scolomfr-voc-015-num-980': {'label': 'histoire et géographie',
                                        'edubases': ['Géographie', 'Histoire'],
                                        'scolomfr': ['géographie',
                                                     'histoire et géographie',
                                                     'géographie (3e)',
                                                     'géographie (4e)',
                                                     'géographie (5e)',
                                                     'géographie (6e)',
                                                     'histoire',
                                                     'histoire (3e)',
                                                     'histoire (4e)',
                                                     'histoire (5e)',
                                                     'histoire (6e)',
                                                     'histoire contemporaine',
                                                     'histoire des arts (cycle 4)',
                                                     'histoire des arts (lycée 2015)',
                                                     'histoire et géographie',
                                                     'histoire-géographie (bac pro)',
                                                     'histoire-géographie (CAP)',
                                                     'histoire et géographie (cycle 3)',
                                                     'histoire et géographie (cycle 4)',
                                                     'histoire et géographie (lycée 2015)',
                                                     'histoire et géographie (discipline)',
                                                     'histoire et géographie (enseignement commun)',
                                                     'histoire-géographie, géopolitique et sciences politiques (enseignement de spécialité)',
                                                     'la longue histoire de l\'humanité et des migrations (histoire 6e)',
                                                     ]},
           'scolomfr-voc-015-num-1430': {'label': 'langues vivantes (étrangères ou régionales)',
                                         'edubases': ['Langues vivantes'],
                                         'scolomfr': [
                                             'connaissances culturelles et linguistiques (langues vivantes cycle 4)',
                                             'langages artistiques (langues vivantes cycle 4)',
                                             'langues vivantes',
                                             'langues vivantes (CAP)',
                                             'langues vivantes (Bac Pro)',
                                             'langues vivantes (lycée 2015)',
                                             'langues vivantes (enseignement commun, enseignement optionnel)',
                                             'langues vivantes (étrangères ou régionales) (discipline)',
                                             'langues vivantes étrangères ou régionales (cycle 2)',
                                             'langues vivantes étrangères ou régionales (cycle 3)',
                                             'langues vivantes étrangères ou régionales (cycle 4)',
                                             'langues vivantes étrangères ou régionales (lver, cycles 2-4)',
                                             'lire (langues vivantes cycle 4)',
                                             'lire et comprendre (lver cycle 4)',
                                             'présenter, décrire (langues vivantes cycle 4)',
                                             'rencontres avec d\'autres cultures (langues vivantes cycle 4)',
                                             'repères culturels historiques et géographiques (langues vivantes cycle 4)',
                                             'écouter et comprendre (langues vivantes cycle 3)',
                                             'écouter et comprendre (langues vivantes cycle 4)',
                                             'écrire (lver cycle 4)',
                                             'écrire et réagir à l\'écrit (langues vivantes cycle 4)', 'italien',
                                             'italien (lver)',
                                             'italien (lver, cycles 2-4)',
                                             'italien (lycée 2015)',
                                             'langues, littératures et cultures étrangères - italien (enseignement de spécialité)',
                                             'langues, littératures et cultures étrangères - allemand (enseignement de spécialité)',
                                             'anglais',
                                             'anglais (discipline)',
                                             'anglais (lver)',
                                             'anglais (lycée 2015)',
                                             'langues, littératures et cultures étrangères - anglais (enseignement de spécialité)',
                                             'langues, littératures et cultures étrangères - anglais (enseignement de spécialité)',
                                             'espagnol', 'espagnol (lver)',
                                             'espagnol (lver, cycles 2-4)',
                                             'espagnol (lycée 2015)',
                                             'chinois',
                                             'allemand',
                                             'allemand',
                                             'allemand (lycée 2015)',
                                             'allemand (lver, cycles 2-4)',
                                             'allemand (enseignement commun, optionnel)']},
           'scolomfr-voc-015-num-919': {'label': 'mathématiques',
                                        'edubases': ['Mathématiques'],
                                        'scolomfr': [
                                            'algorithmique et programmation (mathématiques cycle 4)',
                                            'algorithmique (numérique et sciences informatiques 1re g)',
                                            'algorithmique (numérique et sciences informatiques, terminale g)',
                                            'algorithmique appliquée',
                                            'mathématiques',
                                            'mathématiques (cap)',
                                            'mathématiques (cycle 3)',
                                            'mathématiques (cycle 4)',
                                            'mathématiques (discipline)',
                                            'mathématiques (enseignement commun)',
                                            'mathématiques (enseignement de spécialité)',
                                            'mathématiques (lycée 2015)',
                                            'mathématiques (bac pro)',
                                            'mathématiques (cycle 2)',
                                            'mathématiques complémentaires (enseignement optionnel)',
                                        ]},
           'scolomfr-voc-015-num-7755': {'label': 'sciences humaines',
                                         'edubases': ['Philosophie'],
                                         'scolomfr': ['philosophie',
                                                      'humanités, littérature et philosophie (enseignement de spécialité)']},
           'scolomfr-voc-015-num-1831': {'label': 'physique-chimie',
                                         'edubases': ['Physique - Chimie'],
                                         'scolomfr': ['physique',
                                                      'sciences physiques',
                                                      'chimie',
                                                      'physique-chimie',
                                                      'physique-chimie (CAP)',
                                                      'physique-chimie (cycle 4)',
                                                      'physique-chimie (discipline)',
                                                      'physique-chimie (enseignement commun)',
                                                      'physique-chimie (enseignement de spécialité)',
                                                      'physique-chimie (lycée 2015)',
                                                      'physique-chimie (bac pro)',
                                                      'sciences physiques et chimiques appliquées',
                                                      'sciences physiques et chimiques au lycée professionnel',
                                                      ]},
           'scolomfr-voc-015-num-6364': {'label': 'sciences économiques et sociales',
                                         'edubases': ['SES'],
                                         'scolomfr': ['sciences économiques et sociales',
                                                      'sciences économiques et sociales (discipline)',
                                                      'sciences économiques et sociales (enseignement commun)',
                                                      'sciences économiques et sociales (enseignement de spécialité)', ]},
           'scolomfr-voc-015-num-1832': {'label': 'sciences de la vie et de la Terre',
                                         'edubases': ['SVT'],
                                         'scolomfr': ['sciences de la vie et de la terre (cycle 4)',
                                                      'sciences de la vie et de la terre (discipline)',
                                                      'sciences de la vie et de la terre (enseignement de spécialité)',
                                                      'sciences de la vie et de la terre (lycée 2015)',
                                                      'chimie, biochimie, sciences du vivant',
                                                      'sciences de la vie et de la terre',
                                                      'sciences de la vie et de la terre (cycle 4)',
                                                      'sciences de la vie et de la terre (discipline)',
                                                      'sciences de la vie et de la terre (enseignement commun)',
                                                      'sciences de la vie et de la terre (enseignement de spécialité)',
                                                      'le corps humain et la santé (sciences de la vie et de la Terre cycle 4)',
                                                      'sciences de la vie et de la terre',
                                                      ]},
           'scolomfr-voc-015-num-6365': {'label': 'ST2S',
                                         'edubases': [],
                                         'scolomfr': ['sciences et techniques sanitaires et sociales']},
           'scolomfr-voc-015-num-1834': {'label': 'technologie',
                                         'edubases': ['Technologie'],
                                         'scolomfr': ['technologie',
                                                      'sciences et technologie (cycle 3)',
                                                      'sciences numériques et technologie (enseignement commun)',
                                                      'technologie (cycle 4)']},
           'scolomfr-voc-015-num-6369': {'label': 'STMG',
                                         'edubases': ['Économie et gestion'],
                                         'scolomfr': ['économie', 'culture économique', 'économie - gestion',
                                                      'économie et gestion',
                                                      'économie-droit',
                                                      'économie et gestion des entreprises - législation du travail',
                                                      'économie gestion organisation du travail',
                                                      'comptabilité et gestion', 'gestion-administration',
                                                      'gestion appliquée',
                                                      'comptabilité et gestion (bts)',
                                                      'comptabilité',
                                                      'gestion',
                                                      'gestion de la PME',
                                                      'gestion et finance',
                                                      'gestion et management',
                                                      'gestion-administration (bac pro)',
                                                      'management des entreprises',
                                                      'management des organisations',
                                                      'droit et économie (enseignement de spécialité)',
                                                      'sciences de gestion'
                                                      ]},
           'scolomfr-voc-015-num-6365': {'label': 'ST2S',
                                         'edubases': ['Biotech-ST2S'],
                                         'scolomfr': ['biotech-st2s', 'biotechnologies (bts)', 'biologie',
                                                      'ST2S (discipline technologique)',
                                                      'sciences et techniques sanitaires et sociales',
                                                      'biologie et physiopathologie humaines']},
           'scolomfr-voc-015-num-7816': {'label': 'prévention-santé-environnement',
                                         'edubases': [''],
                                         'scolomfr': ['prévention - santé - environnement',
                                                      'prévention-santé-environnement (bac pro)',
                                                      'prévention-santé-environnement (cap)',
                                                      'sciences appliquées à l\'alimentation, à l\'hygiène et à l\'environnement']},
           'scolomfr-voc-015-num-1200': {'label': 'éducation musicale (discipline)',
                                         'edubases': [''],
                                         'scolomfr': [
                                             'arrangement, réorganisation musicale (éducation musicale cycle 4)',
                                             'chanter et interpréter (éducation musicale cycle 3)',
                                             'culture musicale et artistique (éducation musicale cycle 4)'
                                             'échanger, partager et argumenter (éducation musicale cycle 3)',
                                             'échanger, partager, argumenter, débattre (éducation musicale cycle 4)',
                                             'écouter, comparer, commenter (éducation musicale cycle 3)',
                                             'explorer, imaginer et créer (éducation musicale cycle 3)',
                                             "l'analyse objective dans l'approche critique (éducation musicale cycle 4)",
                                             'musique, esthétique et contexte (éducation musicale cycle 4)',
                                             'repères techniques et culturels (éducation musicale cycle 4)',
                                             "réaliser des projets musicaux d'interprétation ou de création (cycle 4)",
                                             "s'enrichir de la diversité des gouts personnels et des esthétiques (éducation musicale cycle 4)",
                                             'écouter, comparer, construire une culture musicale commune (cycle 4)',
                                             'éducation musicale',
                                             'éducation musicale (cycle 3)',
                                             'éducation musicale (cycle 4)',
                                             'éducation musicale (discipline)',
                                             'musique (enseignement de spécialité)',
                                             'musique option-pratique artistique',
                                             'musique',

                                         ]},
           }
