domains = {'scolomfr-voc-015-num-1179': {'edubases': ['Arts plastiques'],
                                         'scolomfr': ['arts plastiques (cycle 3)',
                                                      'arts plastiques (cycle 4)',
                                                      'arts plastiques (enseignement de spécialité)',
                                                      'arts plastiques (enseignement optionnel)']},
           'scolomfr-voc-015-num-1548': {'edubases': ['EMC'],
                                         'scolomfr': ['éducation civique',
                                                      'enseignement moral et civique (enseignement commun)',
                                                      'enseignement moral et civique (cycle 4)',
                                                      'enseignement moral et civique (discipline)',
                                                      'enseignement moral et civique (lycée 2015)',
                                                      'éducation civique',
                                                      'éducation civique, juridique et sociale'
                                                      ]},
           'scolomfr-voc-015-num-1032': {'edubases': ['EPS'],
                                         'scolomfr': ['éducation physique et sportive (cycle 3)',
                                                      'éducation physique et sportive (cycle 4)']},
           'scolomfr-voc-015-num-1333': {'edubases': ['Français'],
                                         'scolomfr': ['français',
                                                      'français (CAP)',
                                                      'français (cycle 3)',
                                                      'français (cycle 4)',
                                                      'français (discipline)',
                                                      'français (enseignement commun)',
                                                      'français et histoire géographie',
                                                      'français et littérature',
                                                      'fle (français langue étrangère)',
                                                      'français (Bac Pro)',
                                                      'français (cycle 2)',
                                                      'français langue étrangère',
                                                      'français, histoire-géographie-éducation civique',
                                                      'comprendre le fonctionnement de la langue (cycle 3)',
                                                      'comprendre le fonctionnement de la langue (cycle 4)',
                                                      'lecture',
                                                      'lecture (français, cap)',
                                                      'lecture et compréhension de documents (français cycle 4)',
                                                      'lecture et compréhension de l\'écrit (français cycle 2)',
                                                      'lecture et compréhension de l\'écrit (français cycle 3)',
                                                      'culture littéraire et artistique (français cycle 3)',
                                                      'culture littéraire et artistique (français cycle 4)',
                                                      'écriture',
                                                      'écriture (cycle 1)',
                                                      'vocabulaire (français cycle 4)',
                                                      'vocabulaire',
                                                      'étude de la langue (grammaire, orthographe, lexique)'
                                                      ]},
           'scolomfr-voc-015-num-6360': {'edubases': ['Grec ancien', 'Latin'],
                                         'scolomfr': ['latin',
                                                      'langues et cultures de l\'Antiquité (discipline)',
                                                      'Langues et cultures de l\'antiquité (grec)',
                                                      'langues et cultures de l\'Antiquité (enseignement facultatif cycle 4)',
                                                      'langues et cultures de l\'antiquité (latin)']},
           'scolomfr-voc-015-num-980': {'edubases': ['Géographie', 'Histoire'],
                                        'scolomfr': ['géographie',
                                                     'histoire et géographie',
                                                     'géographie (3e)',
                                                     'géographie (4e)',
                                                     'géographie (5e)',
                                                     'géographie (6e)',
                                                     'histoire',
                                                     'histoire (3e)',
                                                     'histoire (4e)',
                                                     'histoire (5e)',
                                                     'histoire (6e)',
                                                     'histoire contemporaine',
                                                     'histoire des arts (cycle 4)',
                                                     'histoire des arts (lycée 2015)',
                                                     'histoire et géographie',
                                                     'histoire-géographie (bac pro)',
                                                     'histoire-géographie (CAP)',
                                                     'histoire et géographie (cycle 3)',
                                                     'histoire et géographie (cycle 4)',
                                                     'histoire et géographie (discipline)',
                                                     'histoire et géographie (enseignement commun)',
                                                     'histoire-géographie, géopolitique et sciences politiques (enseignement de spécialité)', ]},
           'scolomfr-voc-015-num-1430': {'edubases': ['Langues vivantes'],
                                         'scolomfr': [
                                             'connaissances culturelles et linguistiques (langues vivantes cycle 4)',
                                             'langages artistiques (langues vivantes cycle 4)',
                                             'langues vivantes (CAP)',
                                             'langues vivantes (Bac Pro)',
                                             'langues vivantes (enseignement commun, enseignement optionnel)',
                                             'langues vivantes (étrangères ou régionales) (discipline)',
                                             'langues vivantes étrangères ou régionales (cycle 2)',
                                             'langues vivantes étrangères ou régionales (cycle 3)',
                                             'langues vivantes étrangères ou régionales (cycle 4)',
                                             'langues vivantes étrangères ou régionales (lver, cycles 2-4)',
                                             'lire (langues vivantes cycle 4)',
                                             'lire et comprendre (lver cycle 4)',
                                             'présenter, décrire (langues vivantes cycle 4)',
                                             'rencontres avec d\'autres cultures (langues vivantes cycle 4)',
                                             'repères culturels historiques et géographiques (langues vivantes cycle 4)',
                                             'écouter et comprendre (langues vivantes cycle 3)',
                                             'écouter et comprendre (langues vivantes cycle 4)',
                                             'écrire (lver cycle 4)',
                                             'écrire et réagir à l\'écrit (langues vivantes cycle 4)', 'italien',
                                             'italien (lver)',
                                             'italien (lver, cycles 2-4)',
                                             'langues, littératures et cultures étrangères - italien (enseignement de spécialité)',
                                             'langues, littératures et cultures étrangères - allemand (enseignement de spécialité)',
                                             'anglais',
                                             'anglais (discipline)',
                                             'anglais (lver)',
                                             'langues, littératures et cultures étrangères - anglais (enseignement de spécialité)',
                                             'langues, littératures et cultures étrangères - anglais (enseignement de spécialité)',
                                             'espagnol', 'espagnol (lver)',
                                             'espagnol (lver, cycles 2-4)',
                                             'chinois',
                                             'allemand',
                                             'allemand',
                                             'allemand (lycée 2015)',
                                             'allemand (lver, cycles 2-4)',
                                             'allemand (enseignement commun, optionnel)']},
           'scolomfr-voc-015-num-919': {'edubases': ['Mathématiques'],
                                        'scolomfr': [
                                            'algorithmique et programmation (mathématiques cycle 4)',
                                            'algorithmique (numérique et sciences informatiques 1re g)',
                                            'algorithmique (numérique et sciences informatiques, terminale g)',
                                            'algorithmique appliquée',
                                            'mathématiques',
                                            'mathématiques (cap)',
                                            'mathématiques (cycle 3)',
                                            'mathématiques (cycle 4)',
                                            'mathématiques (discipline)',
                                            'mathématiques (enseignement commun)',
                                            'mathématiques (enseignement de spécialité)',
                                            'mathématiques (lycée 2015)',
                                            'mathématiques (bac pro)',
                                            'mathématiques (cycle 2)',
                                            'mathématiques complémentaires (enseignement optionnel)',
                                        ]},
           'scolomfr-voc-015-num-7755': {'edubases': ['Philosophie'],
                                         'scolomfr': ['philosophie',
                                                      'humanités, littérature et philosophie (enseignement de spécialité)']},
           'scolomfr-voc-015-num-1831': {'edubases': ['Physique - Chimie'],
                                         'scolomfr': ['physique',
                                                      'sciences physiques',
                                                      'chimie',
                                                      'physique-chimie',
                                                      'physique-chimie (CAP)',
                                                      'physique-chimie (cycle 4)',
                                                      'physique-chimie (discipline)',
                                                      'physique-chimie (enseignement commun)',
                                                      'physique-chimie (enseignement de spécialité)',
                                                      'physique-chimie (bac pro)',
                                                      'sciences physiques et chimiques appliquées',
                                                      'sciences physiques et chimiques au lycée professionnel',
                                                      ]},
           'scolomfr-voc-015-num-6364': {'edubases': ['SES'],
                                         'scolomfr': ['sciences économiques et sociales',
                                                      'sciences économiques et sociales (discipline)',
                                                      'sciences économiques et sociales (enseignement commun)',
                                                      'sciences économiques et sociales (enseignement de spécialité)', ]},
           'scolomfr-voc-015-num-1832': {'edubases': ['SVT'],
                                         'scolomfr': ['sciences de la vie et de la terre (cycle 4)',
                                                      'sciences de la vie et de la terre (discipline)',
                                                      'sciences de la vie et de la terre (enseignement de spécialité)',
                                                      'sciences de la vie et de la terre (lycée 2015)',
                                                      'chimie, biochimie, sciences du vivant',
                                                      'sciences de la vie et de la terre',
                                                      'sciences de la vie et de la terre (cycle 4)',
                                                      'sciences de la vie et de la terre (discipline)',
                                                      'sciences de la vie et de la terre (enseignement commun)',
                                                      'sciences de la vie et de la terre (enseignement de spécialité)',
                                                      'sciences de la vie et de la terre',
                                                      ]},
           'scolomfr-voc-015-num-6365': {'edubases': [],
                                         'scolomfr': ['sciences et techniques sanitaires et sociales']},
           'scolomfr-voc-015-num-1834': {'edubases': ['Technologie'],
                                         'scolomfr': ['technologie',
                                                      'sciences et technologie (cycle 3)',
                                                      'sciences numériques et technologie (enseignement commun)',
                                                      'technologie (cycle 4)']},
           'scolomfr-voc-015-num-6369': {'edubases': ['Économie et gestion'],
                                         'scolomfr': ['économie', 'culture économique', 'économie - gestion',
                                                      'économie et gestion',
                                                      'économie-droit',
                                                      'économie et gestion des entreprises - législation du travail',
                                                      'économie gestion organisation du travail',
                                                      'comptabilité et gestion', 'gestion-administration',
                                                      'gestion appliquée',
                                                      'comptabilité et gestion (bts)',
                                                      'comptabilité',
                                                      'gestion',
                                                      'gestion de la PME',
                                                      'gestion et finance',
                                                      'gestion et management',
                                                      'gestion-administration (bac pro)',
                                                      'management des entreprises',
                                                      'management des organisations',
                                                      'droit et économie (enseignement de spécialité)',
                                                      'sciences de gestion'
                                                      ]},
           'scolomfr-voc-015-num-6365': {'edubases': ['Biotech-ST2S'],
                                         'scolomfr': ['biotech-st2s', 'biotechnologies (bts)', 'biologie',
                                                      'biologie et physiopathologie humaines']},
           'scolomfr-voc-015-num-7816': {'edubases': [''],
                                         'scolomfr': ['prévention - santé - environnement',
                                                      'prévention-santé-environnement (bac pro)',
                                                      'prévention-santé-environnement (cap)',
                                                      'sciences appliquées à l\'alimentation, à l\'hygiène et à l\'environnement']},
           }
