levels = {"scolomfr-voc-022-num-004": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-004", "scolomfr-voc-022-num-002",
                                                    "scolomfr-voc-022-num-241", "scolomfr-voc-022-num-617",
                                                    "scolomfr-voc-022-num-003"], "label": "toute petite section"},
          "scolomfr-voc-022-num-005": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-005", "scolomfr-voc-022-num-002",
                                                    "scolomfr-voc-022-num-241", "scolomfr-voc-022-num-617",
                                                    "scolomfr-voc-022-num-003"], "label": "petite section"},
          "scolomfr-voc-022-num-006": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-006", "scolomfr-voc-022-num-002",
                                                    "scolomfr-voc-022-num-241", "scolomfr-voc-022-num-617",
                                                    "scolomfr-voc-022-num-003"], "label": "moyenne section"},
          "scolomfr-voc-022-num-007": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-007", "scolomfr-voc-022-num-002",
                                                    "scolomfr-voc-022-num-241", "scolomfr-voc-022-num-617",
                                                    "scolomfr-voc-022-num-009"], "label": "grande section"},
          "scolomfr-voc-022-num-010": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-010", "scolomfr-voc-022-num-008",
                                                    "scolomfr-voc-022-num-242", "scolomfr-voc-022-num-619",
                                                    "scolomfr-voc-022-num-009"], "label": "CP"},
          "scolomfr-voc-022-num-011": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-011", "scolomfr-voc-022-num-008",
                                                    "scolomfr-voc-022-num-242", "scolomfr-voc-022-num-619",
                                                    "scolomfr-voc-022-num-009"], "label": "CE1"},
          "scolomfr-voc-022-num-013": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-013", "scolomfr-voc-022-num-008",
                                                    "scolomfr-voc-022-num-242", "scolomfr-voc-022-num-619",
                                                    "scolomfr-voc-022-num-012"], "label": "CE2"},
          "scolomfr-voc-022-num-014": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-014", "scolomfr-voc-022-num-008",
                                                    "scolomfr-voc-022-num-242", "scolomfr-voc-022-num-620",
                                                    "scolomfr-voc-022-num-012"], "label": "CM1"},
          "scolomfr-voc-022-num-015": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-015", "scolomfr-voc-022-num-008",
                                                    "scolomfr-voc-022-num-242", "scolomfr-voc-022-num-620",
                                                    "scolomfr-voc-022-num-012"], "label": "CM2"},
          "scolomfr-voc-022-num-018": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-018", "scolomfr-voc-022-num-016",
                                                    "scolomfr-voc-022-num-066", "scolomfr-voc-022-num-239",
                                                    "scolomfr-voc-022-num-620", "scolomfr-voc-022-num-017"],
                                       "label": "6e"}, "scolomfr-voc-022-num-020": {"edubases": [], "scolomfr": [
        "scolomfr-voc-022-num-020", "scolomfr-voc-022-num-016", "scolomfr-voc-022-num-066", "scolomfr-voc-022-num-239",
        "scolomfr-voc-022-num-621", "scolomfr-voc-022-num-019"], "label": "5e"},
          "scolomfr-voc-022-num-021": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-021", "scolomfr-voc-022-num-016",
                                                    "scolomfr-voc-022-num-066", "scolomfr-voc-022-num-239",
                                                    "scolomfr-voc-022-num-621", "scolomfr-voc-022-num-019"],
                                       "label": "4e"}, "scolomfr-voc-022-num-023": {"edubases": [], "scolomfr": [
        "scolomfr-voc-022-num-023", "scolomfr-voc-022-num-016", "scolomfr-voc-022-num-066", "scolomfr-voc-022-num-239",
        "scolomfr-voc-022-num-621", "scolomfr-voc-022-num-022"], "label": "3e"},
          "scolomfr-voc-022-num-608": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-608", "scolomfr-voc-022-num-023",
                                                    "scolomfr-voc-022-num-016"], "label": "3e d'insertion"},
          "scolomfr-voc-022-num-129": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-129", "scolomfr-voc-022-num-237",
                                                    "scolomfr-voc-022-num-123", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "1re STD2A"},
          "scolomfr-voc-022-num-131": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-131", "scolomfr-voc-022-num-237",
                                                    "scolomfr-voc-022-num-123", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "1re STI2D"},
          "scolomfr-voc-022-num-132": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-132", "scolomfr-voc-022-num-237",
                                                    "scolomfr-voc-022-num-123", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "1re STL"},
          "scolomfr-voc-022-num-133": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-133", "scolomfr-voc-022-num-237",
                                                    "scolomfr-voc-022-num-123", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "1re STMG"},
          "scolomfr-voc-022-num-134": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-134", "scolomfr-voc-022-num-237",
                                                    "scolomfr-voc-022-num-123", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "1re ST2S"},
          "scolomfr-voc-022-num-135": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-135", "scolomfr-voc-022-num-237",
                                                    "scolomfr-voc-022-num-123", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "1re techno hôtellerie"},
          "scolomfr-voc-022-num-136": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-136", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-066", "scolomfr-voc-022-num-240",
                                                    "scolomfr-voc-022-num-084"],
                                       "label": "2de générale et technologique"},
          "scolomfr-voc-022-num-138": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-138", "scolomfr-voc-022-num-141",
                                                    "scolomfr-voc-022-num-065"], "label": "3e professionnelle"},
          "scolomfr-voc-022-num-201": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-201", "scolomfr-voc-022-num-088",
                                                    "scolomfr-voc-022-num-142", "scolomfr-voc-022-num-240",
                                                    "scolomfr-voc-022-num-085", "scolomfr-voc-022-num-230"],
                                       "label": "terminale générale"}, "scolomfr-voc-022-num-043": {"edubases": [],
                                                                                                    "scolomfr": [
                                                                                                        "scolomfr-voc-022-num-043",
                                                                                                        "scolomfr-voc-022-num-211",
                                                                                                        "scolomfr-voc-022-num-088",
                                                                                                        "scolomfr-voc-022-num-142",
                                                                                                        "scolomfr-voc-022-num-240",
                                                                                                        "scolomfr-voc-022-num-085",
                                                                                                        "scolomfr-voc-022-num-233"],
                                                                                                    "label": "terminale ST2S"},
          "scolomfr-voc-022-num-044": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-044", "scolomfr-voc-022-num-211",
                                                    "scolomfr-voc-022-num-088", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "terminale STD2A"},
          "scolomfr-voc-022-num-047": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-047", "scolomfr-voc-022-num-211",
                                                    "scolomfr-voc-022-num-088", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "terminale STI2D"},
          "scolomfr-voc-022-num-048": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-048", "scolomfr-voc-022-num-211",
                                                    "scolomfr-voc-022-num-088", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "terminale STL"},
          "scolomfr-voc-022-num-049": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-049", "scolomfr-voc-022-num-211",
                                                    "scolomfr-voc-022-num-088", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"],
                                       "label": "terminale techno hôtellerie"},
          "scolomfr-voc-022-num-083": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-083", "scolomfr-voc-022-num-211",
                                                    "scolomfr-voc-022-num-088", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "terminale STMG"},
          "scolomfr-voc-022-num-212": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-212", "scolomfr-voc-022-num-211",
                                                    "scolomfr-voc-022-num-088", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "terminale TMD"},
          "scolomfr-voc-022-num-027": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-027", "scolomfr-voc-022-num-165",
                                                    "scolomfr-voc-022-num-065", "scolomfr-voc-022-num-240",
                                                    "scolomfr-voc-022-num-084"], "label": "2de professionnelle"},
          "scolomfr-voc-022-num-089": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-089", "scolomfr-voc-022-num-050",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085"],
                                       "label": "terminale pro domaine de la production"},
          "scolomfr-voc-022-num-090": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-090", "scolomfr-voc-022-num-050",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085"],
                                       "label": "terminale pro domaine des services"},
          "scolomfr-voc-022-num-213": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-213", "scolomfr-voc-022-num-165",
                                                    "scolomfr-voc-022-num-065", "scolomfr-voc-022-num-240"],
                                       "label": "voie BEP"}, "scolomfr-voc-022-num-095": {"edubases": [], "scolomfr": [
        "scolomfr-voc-022-num-095", "scolomfr-voc-022-num-214", "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
        "scolomfr-voc-022-num-240"], "label": "BMA - 1re année"}, "scolomfr-voc-022-num-096": {"edubases": [],
                                                                                               "scolomfr": [
                                                                                                   "scolomfr-voc-022-num-096",
                                                                                                   "scolomfr-voc-022-num-214",
                                                                                                   "scolomfr-voc-022-num-165",
                                                                                                   "scolomfr-voc-022-num-065",
                                                                                                   "scolomfr-voc-022-num-240"],
                                                                                               "label": "BMA - 2e année"},
          "scolomfr-voc-022-num-097": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-097", "scolomfr-voc-022-num-215",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240"], "label": "BP - 1re année"},
          "scolomfr-voc-022-num-098": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-098", "scolomfr-voc-022-num-215",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240"], "label": "BP - 2e année"},
          "scolomfr-voc-022-num-153": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-153", "scolomfr-voc-022-num-221",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-240",
                                                    "scolomfr-voc-022-num-233"], "label": "BT - première"},
          "scolomfr-voc-022-num-154": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-154", "scolomfr-voc-022-num-221",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-240",
                                                    "scolomfr-voc-022-num-233"], "label": "BT - terminale"},
          "scolomfr-voc-022-num-099": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-099", "scolomfr-voc-022-num-222",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240"], "label": "BTM - 1re année"},
          "scolomfr-voc-022-num-100": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-100", "scolomfr-voc-022-num-222",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240"], "label": "BTM - 2e année"},
          "scolomfr-voc-022-num-103": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-103", "scolomfr-voc-022-num-223",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240"], "label": "CAP - 1re année"},
          "scolomfr-voc-022-num-104": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-104", "scolomfr-voc-022-num-223",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240"], "label": "CAP - 2e année"},
          "scolomfr-voc-022-num-288": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-288", "scolomfr-voc-022-num-227",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240"], "label": "FC post niveau IV"},
          "scolomfr-voc-022-num-298": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-298", "scolomfr-voc-022-num-227",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240"], "label": "FC post niveau V"},
          "scolomfr-voc-022-num-231": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-231", "scolomfr-voc-022-num-165",
                                                    "scolomfr-voc-022-num-065", "scolomfr-voc-022-num-240"],
                                       "label": "voie MC"}, "scolomfr-voc-022-num-125": {"edubases": [], "scolomfr": [
        "scolomfr-voc-022-num-125", "scolomfr-voc-022-num-127", "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
        "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085"], "label": "1re pro domaine de la production"},
          "scolomfr-voc-022-num-126": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-126", "scolomfr-voc-022-num-127",
                                                    "scolomfr-voc-022-num-165", "scolomfr-voc-022-num-065",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085"],
                                       "label": "1re pro domaine des services"},
          "scolomfr-voc-022-num-238": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-238", "scolomfr-voc-022-num-237",
                                                    "scolomfr-voc-022-num-123", "scolomfr-voc-022-num-142",
                                                    "scolomfr-voc-022-num-240", "scolomfr-voc-022-num-085",
                                                    "scolomfr-voc-022-num-233"], "label": "1re TMD"},
          "scolomfr-voc-022-num-640": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-640", "scolomfr-voc-022-num-237",
                                                    "scolomfr-voc-022-num-123", "scolomfr-voc-022-num-142"],
                                       "label": "1re STHR"}, "scolomfr-voc-022-num-641": {"edubases": [], "scolomfr": [
        "scolomfr-voc-022-num-641", "scolomfr-voc-022-num-211", "scolomfr-voc-022-num-088", "scolomfr-voc-022-num-142"],
                                                                                          "label": "terminale STHR"},
          "scolomfr-voc-022-num-650": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-650", "scolomfr-voc-022-num-136",
                                                    "scolomfr-voc-022-num-142", "scolomfr-voc-022-num-240",
                                                    "scolomfr-voc-022-num-084", "scolomfr-voc-022-num-233"],
                                       "label": "2de STHR"}, "scolomfr-voc-022-num-139": {"edubases": [], "scolomfr": [
        "scolomfr-voc-022-num-139", "scolomfr-voc-022-num-141", "scolomfr-voc-022-num-065"],
                                                                                          "label": "4e professionnelle"},
          "scolomfr-voc-022-num-146": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-146", "scolomfr-voc-022-num-123",
                                                    "scolomfr-voc-022-num-142", "scolomfr-voc-022-num-240",
                                                    "scolomfr-voc-022-num-085", "scolomfr-voc-022-num-230"],
                                       "label": "1re générale"}, "scolomfr-voc-022-num-150": {"edubases": [],
                                                                                              "scolomfr": [
                                                                                                  "scolomfr-voc-022-num-150",
                                                                                                  "scolomfr-voc-022-num-140"],
                                                                                              "label": "ASSEH - 1er degré"},
          "scolomfr-voc-022-num-151": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-151", "scolomfr-voc-022-num-140"],
                                       "label": "ASSEH - 2d degré"},
          "scolomfr-voc-022-num-185": {"edubases": [], "scolomfr": ["scolomfr-voc-022-num-185"],
                                       "label": "licence professionnelle"}, "scolomfr-voc-022-num-187": {"edubases": [],
                                                                                                         "scolomfr": [
                                                                                                             "scolomfr-voc-022-num-187",
                                                                                                             "scolomfr-voc-022-num-185"],
                                                                                                         "label": "diplôme de comptabilité et gestion"},
          "scolomfr-voc-022-num-101": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-101", "scolomfr-voc-022-num-195"],
                                       "label": "BTS - 1re année"}, "scolomfr-voc-022-num-102": {"edubases": [],
                                                                                                 "scolomfr": [
                                                                                                     "scolomfr-voc-022-num-102",
                                                                                                     "scolomfr-voc-022-num-195"],
                                                                                                 "label": "BTS - 2e année"},
          "scolomfr-voc-022-num-111": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-111", "scolomfr-voc-022-num-198"],
                                       "label": "DUT - 1re année"}, "scolomfr-voc-022-num-112": {"edubases": [],
                                                                                                 "scolomfr": [
                                                                                                     "scolomfr-voc-022-num-112",
                                                                                                     "scolomfr-voc-022-num-198"],
                                                                                                 "label": "DUT - 2e année"},
          "scolomfr-voc-022-num-109": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-109", "scolomfr-voc-022-num-226"],
                                       "label": "CPGE - 1re année"}, "scolomfr-voc-022-num-110": {"edubases": [],
                                                                                                  "scolomfr": [
                                                                                                      "scolomfr-voc-022-num-110",
                                                                                                      "scolomfr-voc-022-num-226"],
                                                                                                  "label": "CPGE - 2e année"},
          "scolomfr-voc-022-num-163": {"edubases": [], "scolomfr": ["scolomfr-voc-022-num-163"],
                                       "label": "formation des personnels de l'éducation nationale"},
          "scolomfr-voc-022-num-164": {"edubases": [], "scolomfr": ["scolomfr-voc-022-num-164"],
                                       "label": "formation professionnelle continue des adultes"},
          "scolomfr-voc-022-num-063": {"edubases": [],
                                       "scolomfr": ["scolomfr-voc-022-num-063", "scolomfr-voc-022-num-164"],
                                       "label": "formation continue des personnels de l'éducation nationale"}}
