levels = {
    'scolomfr-voc-022-num-004': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-005': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-006': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-007': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-010': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-011': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-013': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-014': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-015': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-018': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-020': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-021': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-023': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-608': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-129': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-131': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-132': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-133': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-134': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-135': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-136': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-138': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-201': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-043': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-044': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-047': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-048': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-049': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-083': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-212': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-027': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-089': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-090': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-213': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-095': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-096': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-097': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-098': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-153': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-154': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-099': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-100': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-103': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-104': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-288': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-298': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-231': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-125': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-126': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-238': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-640': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-641': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-650': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-139': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-146': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-150': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-151': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-185': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-187': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-101': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-102': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-111': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-112': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-109': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-110': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-163': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-164': {'edubases': [],
                                 'scolomfr': []},
    'scolomfr-voc-022-num-063': {'edubases': [],
                                 'scolomfr': []},
}
